[package]
name = "Autofy"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.28.1"
itertools = "0.14.0"
ratatui = "0.29.0"
rspotify = { version = "0.14.0", features = ["client-ureq", "env-file", "ureq-rustls-tls", "cli"], default-features = false }
